# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Pr端fung
description:          'Eine Sammlung von Zusammenfassungen, die der Vorbereitung f端r die IHK-Abschlusspr端fung f端r die Ausbildung Fachinformatiker Anwendungsentwicklung dient.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Marlon Neumann'
  
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rynnon/Zusammenfassungen


exclude: [vendor]

gems: [jekyll-paginate]
